/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export enum ActionName {
  GetConfig = "api-actions/get-config",
  GetAny = "api-actions/get-any",
  GetMenuConfig = "api-actions/get-menu-config",
  GetOutboxData = "api-actions/get-outbox-data",

  SetMenu = "generic-views/set-menu",
  SetLastRefresh = "generic-views/set-last-refresh",
  AddDevice = "generic-views/add-device",
  RemoveDevice = "generic-views/remove-device",
  SetDeviceState = "generic-views/set-device-state",
  SetGenericConfig = "generic-views/set-generic-config",
  RegisterForm = "generic-views/register-form",
  SetFormField = "generic-views/set-form-field",

  OpenModal = "generic-modals/open-modal",
  CloseModal = "generic-modals/close-modal",
  CloseAllModals = "generic-modals/close-all-modals",
  ReplaceModal = "generic-modals/replace-modal",
  CloseDomainModals = "generic-modals/close-domain-modals",
  SetDeviceErrorModalOpened = "generic-modals/set-device-error-modal-opened",

  AddToast = "generic-toasts/add-toast",
  OpenToast = "generic-toasts/open-toast",
  RemoveToast = "generic-toasts/remove-toast",

  SetBackupProcess = "generic-backups/set-backup-process",
  CleanBackupProcess = "generic-backups/clean-backup-process",
  BackupProcessStatus = "generic-backups/backup-process-status",
  CleanRestoreProcess = "generic-backups/clean-restore-process",
  SetRestoreProcessStatus = "generic-backups/set-restore-process-status",
  SetBackupProcessFileStatus = "generic-backups/set-backup-process-file-status",
  SetRestoreProcessFileStatus = "generic-backups/set-restore-process-file-status",
  CreateBackup = "generic-backups/create-backup",
  RestoreBackup = "generic-backups/restore-backup",
  ChooseRestoreFile = "generic-backups/choose-restore-file",
  RefreshBackupList = "generic-backups/refresh-backup-list",
  LoadBackupMetadata = "generic-backups/load-backup-metadata",

  FileTransferSend = "generic-file-transfer/send",
  PreFileTransferSend = "generic-file-transfer/pre-send",
  ChunkFileTransferSend = "generic-file-transfer/chunk-sent",
  ClearFileTransferSendError = "generic-file-transfer/clear-send-errors",
  PreFileTransferGet = "generic-file-transfer/pre-get",
  FileTransferGet = "generic-file-transfer/get",
  ChunkFileTransferGet = "generic-file-transfer/chunk-get",
  ClearFileTransferGetError = "generic-file-transfer/clear-get-errors",
  TransferDataToDevice = "generic-file-transfer/transfer-data-to-device",

  SetDataTransfer = "generic-data-transfer/set-data-transfer",
  SetDataTransferStatus = "generic-data-transfer/set-data-transfer-status",
  ClearDataTransfer = "generic-data-transfer/clear-data-transfer",
  StartImportAuthorization = "generic-imports/start-import-authorization",
  StartContactsImportToDevice = "generic-imports/start-contacts-import-to-device",
  SetDataTransferProcessStatus = "generic-imports/set-data-transfer-process-status",
  SetDataTransferAbort = "generic-data-transfer/set-data-transfer-abort",
  AbortDataTransfer = "generic-data-transfer/abort-data-transfer",

  StartGoogleAuthorization = "generic-imports/start-google-authorization",
  ImportContactsFromExternalSource = "generic-imports/import-contacts-from-external-source",
  StartImportToDevice = "generic-imports/start-data-transfer-to-device",
  SetImportProcessStatus = "generic-imports/set-data-transfer-process-status",
  SetImportProcessFileStatus = "generic-imports/set-data-transfer-process-file-status",
  CleanImportProcess = "generic-imports/clean-import-process",
  StartContactsFileImport = "generic-imports/start-contacts-file-import",
  GoogleAuthorizeProcess = "generic-imports/google-authorization-process",
  GoogleGetContactsProcess = "generic-imports/google-get-contacts-process",
  SetGoogleAuthDataProcess = "generic-imports/set-google-auth-data-process",
  OutlookAuthorizeProcess = "generic-imports/outlook-authorization-process",
  OutlookGetContactsProcess = "generic-imports/outlook-get-contacts-process",
  SetOutlookAuthDataProcess = "generic-imports/set-outlook-auth-data-process",

  SetDataMigrationSourceDevice = "data-migration/set-source-device",
  SetDataMigrationFeatures = "data-migration/set-features",
  SetDataMigrationStatus = "data-migration/set-status",
  PrepareDataMigrationDevices = "data-migration/prepare-devices",
  ProcessDataMigrationDatabase = "data-migration/process-database",
  TransferMigrationData = "data-migration/transfer",
  ClearMigrationData = "data-migration/clear-data",
  AbortDataMigration = "data-migration/abort",
  AddDataMigrationAbortController = "data-migration/add-abort-controller",
  ClearDataMigrationAbortControllers = "data-migration/clear-abort-controllers",
  SetDataMigrationPureDbTempDirectory = "data-migration/set-pure-db-temp-directory",
  SetDataMigrationPureRestarting = "data-migration/set-pure-restarting",
  SetDataMigrationPureBusy = "data-migration/set-pure-busy",

  HelpSetData = "help/set-data",
  HelpRateArticle = "help/rate-article",

  MscFlashingGetFilesDetails = "msc-flashing/get-files-details",
  MscFlashingSetProcessState = "msc-flashing/set-process-state",
  MscFlashingSetAbort = "msc-flashing/set-abort",
  MscFlashingAbort = "msc-flashing/abort",
  MscFlashingSetInitialState = "msc-flashing/set-initial-state",

  LoadEntities = "entities/load-entities",
  GetEntitiesConfig = "entities/get-entities-config",
  SetEntityData = "entities/set-entity-data",
  GetEntitiesMetadata = "entities/get-entities-metadata",
  GetEntitiesData = "entities/get-entities-data",
  GetEntityData = "entities/get-entity-data",
  ClearEntitiesData = "entities/clear-entities-data",
  DeleteEntitiesData = "entities/delete-entities-data",
  DeleteEntityData = "entities/delete-entity-data",
  CreateEntityData = "entities/create-entity-data",
  UpdateEntityData = "entities/update-entity-data",
  RefreshEntitiesIfMetadataChanged = "entities/refresh-entities-if-metadata-changed",
}
