/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export enum ActionName {
  GetConfig = "api-actions/get-config",
  GetAny = "api-actions/get-any",
  GetMenuConfig = "api-actions/get-menu-config",
  GetOutboxData = "api-actions/get-outbox-data",
  SetMenu = "generic-views/set-menu",
  SetViewLayout = "generic-views/set-view-layout",
  SetViewData = "generic-views/set-view-data",
  ActivateDevice = "generic-views/activate-device",
  DetachDevice = "generic-views/detach-device",
  OpenModal = "generic-modals/open-modal",
  CloseModal = "generic-modals/close-modal",
  CloseAllModals = "generic-modals/close-all-modals",
  ReplaceModal = "generic-modals/replace-modal",
  CloseDomainModals = "generic-modals/close-domain-modals",
  SetBackupProcess = "generic-backups/set-backup-process",
  CleanBackupProcess = "generic-backups/clean-backup-process",
  BackupProcessStatus = "generic-backups/backup-process-status",
  CleanRestoreProcess = "generic-backups/clean-restore-process",
  SetRestoreProcessStatus = "generic-backups/set-restore-process-status",
  SetBackupProcessFileStatus = "generic-backups/set-backup-process-file-status",
  SetRestoreProcessFileStatus = "generic-backups/set-restore-process-file-status",
  CreateBackup = "generic-backups/create-backup",
  RestoreBackup = "generic-backups/restore-backup",
  ChooseRestoreFile = "generic-backups/choose-restore-file",
  RefreshBackupList = "generic-backups/refresh-backup-list",
  LoadBackupMetadata = "generic-backups/load-backup-metadata",
  FileTransferSend = "generic-file-transfer/send",
  PreFileTransferSend = "generic-file-transfer/pre-send",
  ChunkFileTransferSend = "generic-file-transfer/chunk-sent",
  ClearFileTransferSendError = "generic-file-transfer/clear-send-errors",
  PreFileTransferGet = "generic-file-transfer/pre-get",
  FileTransferGet = "generic-file-transfer/get",
  ChunkFileTransferGet = "generic-file-transfer/chunk-get",
  ClearFileTransferGetError = "generic-file-transfer/clear-get-errors",
  StartGoogleAuthorization = "generic-imports/start-google-authorization",
  ImportContactsFromExternalSource = "generic-imports/import-contacts-from-external-source",
  StartDataTransferToDevice = "generic-imports/start-data-transfer-to-device",
  SetDataTransferProcessStatus = "generic-imports/set-data-transfer-process-status",
  SetDataTransferProcessFileStatus = "generic-imports/set-data-transfer-process-file-status",
  CleanImportProcess = "generic-imports/clean-import-process",
  StartContactsFileImport = "generic-imports/start-contacts-file-import",
  GetContactsFromCSV = "generic-imports/get-contacts-from-csv",
  SetDataMigrationSourceDevice = "data-migration/set-source-device",
  SetDataMigrationFeatures = "data-migration/set-features",
  ClearDataMigrationDevice = "data-migration/clear-device",
  SetDataMigrationStatus = "data-migration/set-status",
  StartDataMigration = "data-migration/start",
}
