/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

import {
  black,
  blue1,
  blue2,
  blue3,
  blue4,
  blue5,
  darkOrange,
  green,
  grey1,
  grey2,
  grey3,
  grey4,
  grey5,
  grey6,
  orange,
  red,
  transparentBlack1,
  transparentBlack2,
  transparentBlack3,
  white,
} from "./constants"

export const color = {
  text: {
    accent: grey5,
    action: blue2,
    active: white,
    disabled: grey3,
    error: red,
    primary: black,
    secondary: grey2,
    iconBody: white,
    iconUser: blue3,
    tabHover: grey1,
    actionHover: blue1,
    warning: orange,
    info: grey1,
  },
  background: {
    activity: blue2,
    disabled: grey4,
    icon: blue5,
    main: grey6,
    message: blue5,
    minor: grey5,
    primary: grey1,
    primaryHover: black,
    row: white,
    scroll: grey2,
    super: black,
    chartBar: blue4,
    modal: white,
    modalBackdrop: transparentBlack3,
    error: red,
    lightIcon: white,
    green: green,
  },
  border: {
    white: white,
    error: red,
    hover: grey1,
    list: grey4,
    primary: black,
    secondary: grey4,
    separator: grey4,
    smallSeparator: grey4,
    verticalSeparator: grey3,
    tetheringSeparator: blue3,
    deviceListSeparator: grey5,
    deviceListSeparatorHover: grey4,
    warning: darkOrange,
  },
  boxShadow: {
    full: transparentBlack2,
    light: transparentBlack1,
  },
}
