export const URL_MAIN = {
  root: "/",
  news: "/news",
  overview: "/overview",
  messages: "/messages",
  phone: "/phone",
  music: "/music",
  calendar: "/calendar",
  tools: "/tools",
  meditation: "/meditation",
  filesManager: "/files-manager",
  tethering: "/tethering",
  settings: "/settings",
  help: "/help",
}
