/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

import { contactDatabaseFactory } from "App/contacts/store/contacts.helpers"
import { Contact } from "App/contacts/store/contacts.type"
import { PhoneContacts } from "App/contacts/store/contacts.interface"

export const contactsSeedInput: Contact[] = [
  {
    id: 0,
    firstName: "Sławomir",
    lastName: "Borewicz",
    primaryPhoneNumber: "+71 195 069 214",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "sapiente rem dignissimos sunt",
    ice: false,
    favourite: false,
    blocked: false,
    firstAddressLine: "Malczewskiego 3, Warszawa",
    secondAddressLine: "",
  },
  {
    id: 274970,
    firstName: "",
    lastName: "",
    primaryPhoneNumber: "+71 195 069 214",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "sapiente rem dignissimos sunt",
    ice: true,
    favourite: false,
    blocked: true,
    firstAddressLine: "3284 Klocko Plains",
    secondAddressLine: "",
  },
  {
    id: 664,
    firstName: "",
    lastName: "",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "voluptatem expedita vel",
    ice: false,
    favourite: false,
    blocked: false,
    firstAddressLine: "55727 Kelly Expressway",
    secondAddressLine: "",
  },
  {
    id: 999999999,
    firstName: "",
    lastName: "",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "",
    email: "",
    note: "sint quasi quis saepe",
    ice: true,
    favourite: false,
    blocked: false,
    firstAddressLine: "",
    secondAddressLine: "West Gaetano",
  },
  {
    id: 9999999991,
    firstName: "",
    lastName: "",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "ducimus provident",
    ice: true,
    favourite: false,
    blocked: false,
    firstAddressLine: "",
    secondAddressLine: "New Coty",
  },
  {
    id: 9999999992,
    firstName: "",
    lastName: "",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "",
    email: "",
    note: "molestias et dolorum",
    ice: false,
    favourite: false,
    blocked: false,
    firstAddressLine: "",
    secondAddressLine: "Saulland",
  },
  {
    id: 9999999993,
    firstName: "",
    lastName: "Hayes",
    primaryPhoneNumber: "+08 341 329 760",
    secondaryPhoneNumber: "+82 192 423 122",
    email: "",
    note: "qui quibusdam",
    ice: true,
    favourite: false,
    blocked: false,
    firstAddressLine: "",
    secondAddressLine: "",
  },
  {
    id: 9999999994,
    firstName: "Heaven",
    lastName: "Ritchie",
    primaryPhoneNumber: "+93 794 940 260",
    secondaryPhoneNumber: "+90 497 907 015",
    email: "",
    note: "id rerum et magnam",
    ice: true,
    favourite: false,
    blocked: true,
    firstAddressLine: "",
    secondAddressLine: "",
  },
  {
    id: 9999999995,
    firstName: "",
    lastName: "Marvin",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "omnis quia ea",
    ice: true,
    favourite: false,
    blocked: false,
    firstAddressLine: "53692 Giovanni Loop",
    secondAddressLine: "Port Chanelle",
  },
  {
    id: 9999999996,
    firstName: "Meaghan",
    lastName: "",
    primaryPhoneNumber: "+13 975 379 306",
    secondaryPhoneNumber: "",
    email: "",
    note: "nostrum",
    ice: true,
    favourite: false,
    blocked: false,
    firstAddressLine: "7133 Erdman Summit",
    secondAddressLine: "",
  },

  {
    id: 9999999997,
    firstName: "",
    lastName: "Stokes",
    primaryPhoneNumber: "+42 139 089 182",
    secondaryPhoneNumber: "",
    email: "example@mudita.com",
    note: "consequatur ea commodi fugit",
    ice: false,
    favourite: false,
    blocked: true,
    firstAddressLine: "",
    secondAddressLine: "Toybury",
  },
  {
    id: 9999999996,
    firstName: "Tatyana",
    lastName: "Cartwright",
    primaryPhoneNumber: "",
    secondaryPhoneNumber: "+83 559 892 925",
    email: "example@mudita.com",
    note: "voluptas aliquid aut",
    ice: false,
    favourite: true,
    blocked: false,
    firstAddressLine: "43478 Kiley Spurs",
    secondAddressLine: "",
  },
  {
    id: 324934,
    firstName: "Shyann",
    lastName: "Feil",
    primaryPhoneNumber: "+56 159 553 446",
    secondaryPhoneNumber: "",
    email: "",
    note: "",
    ice: false,
    favourite: false,
    blocked: false,
    firstAddressLine: "",
    secondAddressLine: "",
  },
]

export const contactsSeed: PhoneContacts = contactDatabaseFactory(
  contactsSeedInput
)
