export const mockedContacts = [
  {
    id: "b976b151-935f-41bb-87da-07feb2cbf4a2",
    firstName: "Retha",
    lastName: "Senger",
    primaryPhoneNumber: "+26 880 171 031",
    secondaryPhoneNumber: "",
    email: "",
    note: "aspernatur inventore molestiae id",
    ice: true,
    favourite: false,
    blocked: true,
    firstAddressLine: "",
    secondAddressLine: "",
  },
  {
    id: "b976b151-935f-41bb-87da-07fecbf4a2",
    firstName: "Adam",
    lastName: "Blue",
    primaryPhoneNumber: "+26 688 171 031",
    secondaryPhoneNumber: "",
    email: "",
    note: "aspernatur inventore molestiae id",
    ice: true,
    favourite: false,
    blocked: true,
    firstAddressLine: "",
    secondAddressLine: "",
  },
]
