/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export enum ContainerTypeCode {
  Undefined = 0x0000,
  Command = 0x0001,
  Data = 0x0002,
  Response = 0x0003,
  Event = 0x0004,
}

export const containerTypeNames: Record<ContainerTypeCode, string> = {
  [ContainerTypeCode.Undefined]: "Undefined",
  [ContainerTypeCode.Command]: "Command",
  [ContainerTypeCode.Data]: "Data",
  [ContainerTypeCode.Response]: "Response",
  [ContainerTypeCode.Event]: "Event",
}

export enum ContainerCode {
  OpenSession = 0x1002,
  CloseSession = 0x1003,
  GetObjectHandles = 0x1007,
  GetObject = 0x1009,
  GetObjectPropValue = 0x9803,
  ObjectFileName = 0xdc07,
  ObjectFileSize = 0xdc04,
  ObjectFileType = 0xdc02,
  SendObjectInfo = 0x100c,
  SendObject = 0x100d,
  GetDeviceInfo = 0x1001,
  GetStorageIds = 0x1004,
  GetStorageInfo = 0x1005,
  GetNumObjects = 0x1006,
  GetObjectInfo = 0x1008,
  GetThumb = 0x100a,
  DeleteObject = 0x100b,
  InitiateCapture = 0x100e,
  FormatStore = 0x100f,
  ResetDevice = 0x1010,
  SelfTest = 0x1011,
  SetObjectProtection = 0x1012,
  PowerDown = 0x1013,
  GetDevicePropDesc = 0x1014,
  SetDevicePropValue = 0x1016,
  ResetDevicePropValue = 0x1017,
  TerminateOpenCapture = 0x1018,
  MoveObject = 0x1019,
  CopyObject = 0x101a,
  GetPartialObject = 0x101b,
  InitiateOpenCapture = 0x101c,
  GetObjectPropsSupported = 0x9801,
  GetObjectPropDesc = 0x9802,
  SetObjectPropValue = 0x9804,
  GetObjectReferences = 0x9810,
  SetObjectReferences = 0x9811,
  Skip = 0x9820,

  // STATUS
  StatusOk = 0x2001,
  GeneralError = 0x2002,
  SessionNotOpen = 0x2003,
  InvalidTransactionId = 0x2004,
  OperationNotSupported = 0x2005,
  ParameterNotSupported = 0x2006,
  IncompleteTransfer = 0x2007,
  InvalidStorageId = 0x2008,
  InvalidObjectHandle = 0x2009,
  DevicePropNotSupported = 0x200a,
  InvalidObjectFormatCode = 0x200b,
  StoreFull = 0x200c,
  ObjectWriteProtected = 0x200d,
  StoreReadOnly = 0x200e,
  AccessDenied = 0x200f,
  NoThumbnailPresent = 0x2010,
  SelfTestFailed = 0x2011,
  PartialDeletion = 0x2012,
  StoreNotAvailable = 0x2013,
  SpecificationByFormatUnsupported = 0x2014,
  NoValidObjectInfo = 0x2015,
  InvalidCodeFormat = 0x2016,
  UnknownVendorCode = 0x2017,
  CaptureAlreadyTerminated = 0x2018,
  DeviceBusy = 0x2019,
  InvalidParentObject = 0x201a,
  InvalidDevicePropFormat = 0x201b,
  InvalidDevicePropValue = 0x201c,
  InvalidParameter = 0x201d,
  SessionAlreadyOpen = 0x201e,
  TransactionCancelled = 0x201f,
  SpecificationOfDestinationUnsupported = 0x2020,
  InvalidObjectPropCode = 0xa801,
  InvalidObjectPropFormat = 0xa802,
  InvalidObjectPropValue = 0xa803,
  InvalidObjectReference = 0xa804,
  GroupNotSupported = 0xa805,
  InvalidDataset = 0xa806,
  SpecificationByGroupUnsupported = 0xa807,
  SpecificationByDepthUnsupported = 0xa808,
  ObjectTooLarge = 0xa809,
  ObjectPropNotSupported = 0xa80a,
}

export const containerCodeNames: Record<ContainerCode, string> = {
  [ContainerCode.OpenSession]: "Open Session",
  [ContainerCode.CloseSession]: "Close Session",
  [ContainerCode.GetObjectHandles]: "Get Object Handles",
  [ContainerCode.GetObject]: "Get Object",
  [ContainerCode.GetObjectPropValue]: "Get Object Prop Value",
  [ContainerCode.ObjectFileName]: "Object File Name",
  [ContainerCode.ObjectFileSize]: "Object File Size",
  [ContainerCode.ObjectFileType]: "Object File Type",
  [ContainerCode.SendObjectInfo]: "Send Object Info",
  [ContainerCode.SendObject]: "Send Object",
  [ContainerCode.GetDeviceInfo]: "Get Device Info",
  [ContainerCode.GetStorageIds]: "Get Storage IDs",
  [ContainerCode.GetStorageInfo]: "Get Storage Info",
  [ContainerCode.GetNumObjects]: "Get Number of Objects",
  [ContainerCode.GetObjectInfo]: "Get Object Info",
  [ContainerCode.GetThumb]: "Get Thumbnail",
  [ContainerCode.DeleteObject]: "Delete Object",
  [ContainerCode.InitiateCapture]: "Initiate Capture",
  [ContainerCode.FormatStore]: "Format Store",
  [ContainerCode.ResetDevice]: "Reset Device",
  [ContainerCode.SelfTest]: "Self Test",
  [ContainerCode.SetObjectProtection]: "Set Object Protection",
  [ContainerCode.PowerDown]: "Power Down",
  [ContainerCode.GetDevicePropDesc]: "Get Device Prop Description",
  [ContainerCode.SetDevicePropValue]: "Set Device Prop Value",
  [ContainerCode.ResetDevicePropValue]: "Reset Device Prop Value",
  [ContainerCode.TerminateOpenCapture]: "Terminate Open Capture",
  [ContainerCode.MoveObject]: "Move Object",
  [ContainerCode.CopyObject]: "Copy Object",
  [ContainerCode.GetPartialObject]: "Get Partial Object",
  [ContainerCode.InitiateOpenCapture]: "Initiate Open Capture",
  [ContainerCode.GetObjectPropsSupported]: "Get Object Props Supported",
  [ContainerCode.GetObjectPropDesc]: "Get Object Prop Description",
  [ContainerCode.SetObjectPropValue]: "Set Object Prop Value",
  [ContainerCode.GetObjectReferences]: "Get Object References",
  [ContainerCode.SetObjectReferences]: "Set Object References",
  [ContainerCode.Skip]: "Skip",

  // STATUS
  [ContainerCode.StatusOk]: "OK",
  [ContainerCode.GeneralError]: "General Error",
  [ContainerCode.SessionNotOpen]: "Session Not Open",
  [ContainerCode.InvalidTransactionId]: "Invalid Transaction ID",
  [ContainerCode.OperationNotSupported]: "Operation Not Supported",
  [ContainerCode.ParameterNotSupported]: "Parameter Not Supported",
  [ContainerCode.IncompleteTransfer]: "Incomplete Transfer",
  [ContainerCode.InvalidStorageId]: "Invalid Storage ID",
  [ContainerCode.InvalidObjectHandle]: "Invalid Object Handle",
  [ContainerCode.DevicePropNotSupported]: "Device Prop Not Supported",
  [ContainerCode.InvalidObjectFormatCode]: "Invalid Object Format Code",
  [ContainerCode.StoreFull]: "Store Full",
  [ContainerCode.ObjectWriteProtected]: "Object Write Protected",
  [ContainerCode.StoreReadOnly]: "Store Read Only",
  [ContainerCode.AccessDenied]: "Access Denied",
  [ContainerCode.NoThumbnailPresent]: "No Thumbnail Present",
  [ContainerCode.SelfTestFailed]: "Self Test Failed",
  [ContainerCode.PartialDeletion]: "Partial Deletion",
  [ContainerCode.StoreNotAvailable]: "Store Not Available",
  [ContainerCode.SpecificationByFormatUnsupported]: "Specification By Format Unsupported",
  [ContainerCode.NoValidObjectInfo]: "No Valid Object Info",
  [ContainerCode.InvalidCodeFormat]: "Invalid Code Format",
  [ContainerCode.UnknownVendorCode]: "Unknown Vendor Code",
  [ContainerCode.CaptureAlreadyTerminated]: "Capture Already Terminated",
  [ContainerCode.DeviceBusy]: "Device Busy",
  [ContainerCode.InvalidParentObject]: "Invalid Parent Object",
  [ContainerCode.InvalidDevicePropFormat]: "Invalid Device Prop Format",
  [ContainerCode.InvalidDevicePropValue]: "Invalid Device Prop Value",
  [ContainerCode.InvalidParameter]: "Invalid Parameter",
  [ContainerCode.SessionAlreadyOpen]: "Session Already Open",
  [ContainerCode.TransactionCancelled]: "Transaction Cancelled",
  [ContainerCode.SpecificationOfDestinationUnsupported]: "Specification of Destination Unsupported",
  [ContainerCode.InvalidObjectPropCode]: "Invalid Object Prop Code",
  [ContainerCode.InvalidObjectPropFormat]: "Invalid Object Prop Format",
  [ContainerCode.InvalidObjectPropValue]: "Invalid Object Prop Value",
  [ContainerCode.InvalidObjectReference]: "Invalid Object Reference",
  [ContainerCode.GroupNotSupported]: "Group Not Supported",
  [ContainerCode.InvalidDataset]: "Invalid Dataset",
  [ContainerCode.SpecificationByGroupUnsupported]: "Specification By Group Unsupported",
  [ContainerCode.SpecificationByDepthUnsupported]: "Specification By Depth Unsupported",
  [ContainerCode.ObjectTooLarge]: "Object Too Large",
  [ContainerCode.ObjectPropNotSupported]: "Object Prop Not Supported",
};

export const rootObjectHandle = 0xffffffff
export const allStorage = 0xffffffff
