/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export enum HelpTestId {
  MainHeader = "help-main-header",
  MainSubheader = "help-main-subheader",
  SearchInputWrapper = "help-search-input-wrapper",
  SearchInput = "help-search-input",
  SearchResults = "help-search-results",
  SearchResultsItem = "help-search-result-item",
  CategoriesTitle = "help-categories-title",
  CategoriesList = "help-categories-list",
  CategoriesListItem = "help-categories-list-item",
  SubcategoriesList = "help-subcategories-list",
  SubcategoriesListItem = "help-subcategories-list-item",
  SubcategoriesListItemTitle = "help-subcategories-list-item-title",
  SubcategoriesListItemIcon = "help-subcategories-list-item-icon",
  SubcategoryArticlesList = "help-subcategory-articles-list",
  SubcategoryArticlesListItem = "help-subcategory-articles-list-item",
  ArticleBackButton = "help-article-back-button",
  ArticleTitle = "help-article-title",
  ArticleWarning = "help-article-warning",
  ArticleWarningIcon = "help-article-warning-icon",
  ArticleContent = "help-article-content",
  ArticleContentBlock = "help-article-content-block",
  ArticleContentBlockTitle = "help-article-content-block-title",
  ArticleContentBlockText = "help-article-content-block-text",
  ArticleContentBlockExternalLink = "help-article-content-block-external-link",
  ArticleContentBlockInternalLink = "help-article-content-block-internal-link",
  ArticleContentBlockContactSupportLink = "help-article-content-block-contact-support-link",
  ArticleFeedback = "help-article-feedback",
  ArticleFeedbackTitle = "help-article-feedback-title",
  ArticleFeedbackYesButton = "help-article-feedback-yes-button",
  ArticleFeedbackNoButton = "help-article-feedback-no-button",
  ArticleFeedbackThanks = "help-article-feedback-thanks",
  ArticleExternalLinks = "help-article-external-links",
  ArticleExternalLinksTitle = "help-article-external-links-title",
  ArticleExternalLinksList = "help-article-external-links-list",
  ArticleExternalLinksListItem = "help-article-external-links-list-item",
  ArticleFooter = "help-article-footer",
  ArticleFooterTitle = "help-article-footer-title",
  ArticleFooterButton = "help-article-footer-button",
  MainFooter = "help-main-footer",
  MainFooterTitle = "help-main-footer-title",
  MainFooterDescription = "help-main-footer-description",
  MainFooterContactSupportButton = "help-main-footer-contact-support-button",
}
