/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export type OutlookColumn =
  | "First Name"
  | "Middle Name"
  | "Last Name"
  | "Title"
  | "Suffix"
  | "E-mail Address"
  | "E-mail 2 Address"
  | "E-mail 3 Address"
  | "E-mail 4 Address"
  | "Primary Phone"
  | "Home Phone"
  | "Home Phone 2"
  | "Mobile Phone"
  | "Pager"
  | "Home Fax"
  | "Home Address"
  | "Home Street"
  | "Home Street 2"
  | "Home Street 3"
  | "Home Address PO Box"
  | "Home City"
  | "Home State"
  | "Home Postal Code"
  | "Home Country"
  | "Business Phone"
  | "Business Phone 2"
  | "Business Fax"
  | "Company"
  | "Job Title"
  | "Department"
  | "Business Address"
  | "Business Street"
  | "Business Street 2"
  | "Business Street 3"
  | "Business Address PO Box"
  | "Business City"
  | "Business State"
  | "Business Postal Code"
  | "Business Country"
  | "Other Phone"
  | "Other Fax"
  | "Other Address"
  | "Other Street"
  | "Other Street 2"
  | "Other Street 3"
  | "Other Address PO Box"
  | "Other City"
  | "Other State"
  | "Other Postal Code"
  | "Other Country"
  | "Callback"
  | "Car Phone"
  | "ISDN"
  | "Radio Phone"
  | "TTY/TDD Phone"
  | "Telex"
  | "Web Page"
  | "Notes"
// | "Assistant's Phone"
// | "Office Location"
// | "Organizational ID Number"
// | "Profession"
// | "Account"
// | "Spouse"
// | "Children"
// | "Manager's Name"
// | "Assistant's Name"
// | "Referred By"
// | "Company Main Phone"
// | "User 1"
// | "User 2"
// | "User 3"
// | "User 4"
// | "Keywords"
// | "Mileage"
// | "Hobby"
// | "Billing Information"
// | "Directory Server"
// | "Sensitivity"
// | "Priority"
// | "Private"
// | "Categories"
// | "Initials"
// | "Gender"
// | "Birthday"
// | "Anniversary"
// | "Location"
// | "Language"
// | "Internet Free Busy"
