/**
 * Copyright (c) Mudita sp. z o.o. All rights reserved.
 * For licensing, see https://github.com/mudita/mudita-center/blob/master/LICENSE.md
 */

export enum IconType {
  Battery0 = "battery-0",
  Battery1 = "battery-1",
  Battery2 = "battery-2",
  Battery3 = "battery-3",
  Battery4 = "battery-4",
  Battery5 = "battery-5",
  BatteryCharging0 = "battery-charging-0",
  BatteryCharging1 = "battery-charging-1",
  BatteryCharging2 = "battery-charging-2",
  BatteryCharging3 = "battery-charging-3",
  BatteryCharging4 = "battery-charging-4",
  BatteryCharging5 = "battery-charging-5",
  NetworkSignal0 = "network-signal-0",
  NetworkSignal1 = "network-signal-1",
  NetworkSignal2 = "network-signal-2",
  NetworkSignal3 = "network-signal-3",
  NetworkSignal4 = "network-signal-4",
  NoSimCard = "no-sim-card",
  AirplaneMode = "airplane-mode",
  Overview = "overview",
  Close = "close",
  Device = "device",
  Mudita = "mudita",
  Spinner = "spinner",
  SpinnerDark = "spinner-dark",
  Backup = "backup",
  Settings = "settings",
  PasswordShow = "password-show",
  PasswordHide = "password-hide",
  Success = "success",
  Failure = "failure",
  Folder = "folder",
  Contact = "contact",
  ContactsBook = "contacts-book",
  Check = "check",
  Minus = "minus",
  Search = "search",
}
