const { resolve } = require("path")
const tsPaths = require("../../../../tsconfig.base.json").compilerOptions.paths

module.exports = (production) => {
  const resolveConfig = {
    extensions: [".tsx", ".ts", ".js", ".json"],
    alias: {
      // Add libraries aliases generated by NX
      ...Object.entries(tsPaths).reduce((acc, [alias, [path]]) => {
        acc[alias] = resolve(__dirname, "..", "..", "..", "..", path)
        return acc
      }, {}),
      Root: resolve(__dirname, "..", ".."),
      App: resolve(__dirname, "..", "..", "src"),
      Cypress: resolve(__dirname, "..", "..", "cypress"),
      Storybook: resolve(__dirname, "..", "..", ".storybook"),
      Renderer: resolve(__dirname, "..", "..", "src", "renderer"),
      fs: resolve(__dirname, "..", "..", "__mocks__", "fs-mock.js"),
      Core: resolve(__dirname, "..", "..", "..", "..", "libs", "core"),
    },
  }

  if (!production) {
    resolveConfig.alias = {
      ...resolveConfig.alias,
    }
  }

  return resolveConfig
}
