name: Build & Release - production

on:
  push:
    branches:
      - digicert

jobs:
  release:
    runs-on: ${{ matrix.runner_label }}
    strategy:
      matrix:
        runner_label: [windows-nexus]
        node-version: [24.14.0]
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure environment - Windows
        if: matrix.runner_label == 'windows-nexus'
        env:
          FONTS_DIRECTORY_URL: ${{ secrets.FONTS_DIRECTORY_URL }}
          VITE_RELEASES_REPOSITORY_NAME: ${{ secrets.RELEASES_REPOSITORY_NAME }}
          GH_BUILD_TOKEN: ${{ secrets.GH_BUILD_TOKEN }}
          VITE_MUDITA_CENTER_SERVER_URL: ${{ secrets.VITE_MUDITA_CENTER_SERVER_URL }}
          VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
          VITE_MICROSOFT_AUTH_CLIENT_ID: ${{ secrets.VITE_MICROSOFT_AUTH_CLIENT_ID }}
          VITE_ANALYTICS_ENABLED: ${{ secrets.VITE_ANALYTICS_ENABLED }}
          VITE_ANALYTICS_API_SITE_ID: ${{ secrets.VITE_ANALYTICS_API_SITE_ID }}
          VITE_ANALYTICS_API_URL: ${{ secrets.VITE_ANALYTICS_API_URL }}
          ENABLE_DEVTOOLS: ${{ secrets.ENABLE_DEVTOOLS }}
          CI: true
        shell: cmd
        run: |
          SET > .env
          jq -r -j .version apps/app/package.json > apps/app/version
      - name: Configure environment - Mac
        if: matrix.runner_label == 'macos-m-nexus'
        env:
          FONTS_DIRECTORY_URL: ${{ secrets.FONTS_DIRECTORY_URL }}
          VITE_RELEASES_REPOSITORY_NAME: ${{ secrets.RELEASES_REPOSITORY_NAME }}
          GH_BUILD_TOKEN: ${{ secrets.GH_BUILD_TOKEN }}
          VITE_MUDITA_CENTER_SERVER_URL: ${{ secrets.VITE_MUDITA_CENTER_SERVER_URL }}
          VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
          VITE_MICROSOFT_AUTH_CLIENT_ID: ${{ secrets.VITE_MICROSOFT_AUTH_CLIENT_ID }}
          VITE_ANALYTICS_ENABLED: ${{ secrets.VITE_ANALYTICS_ENABLED }}
          VITE_ANALYTICS_API_SITE_ID: ${{ secrets.VITE_ANALYTICS_API_SITE_ID }}
          VITE_ANALYTICS_API_URL: ${{ secrets.VITE_ANALYTICS_API_URL }}
          ENABLE_DEVTOOLS: ${{ secrets.ENABLE_DEVTOOLS }}
          CI: true
        run: |
          printenv > .env
      - name: Configure environment - Linux
        if: matrix.runner_label == 'linux-nexus'
        env:
          FONTS_DIRECTORY_URL: ${{ secrets.FONTS_DIRECTORY_URL }}
          VITE_RELEASES_REPOSITORY_NAME: ${{ secrets.RELEASES_REPOSITORY_NAME }}
          GH_BUILD_TOKEN: ${{ secrets.GH_BUILD_TOKEN }}
          VITE_MUDITA_CENTER_SERVER_URL: ${{ secrets.VITE_MUDITA_CENTER_SERVER_URL }}
          VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
          VITE_MICROSOFT_AUTH_CLIENT_ID: ${{ secrets.VITE_MICROSOFT_AUTH_CLIENT_ID }}
          VITE_ANALYTICS_ENABLED: ${{ secrets.VITE_ANALYTICS_ENABLED }}
          VITE_ANALYTICS_API_SITE_ID: ${{ secrets.VITE_ANALYTICS_API_SITE_ID }}
          VITE_ANALYTICS_API_URL: ${{ secrets.VITE_ANALYTICS_API_URL }}
          ENABLE_DEVTOOLS: ${{ secrets.ENABLE_DEVTOOLS }}
          CI: true
        run: |
          printenv > .env
      - name: Install dependencies
        run: npm run setup
      - name: Prepare electron-builder config - Mac
        if: matrix.runner_label == 'macos-m-nexus'
        run: |
          cp ~/actions-runner/envs/electron-builder.env apps/app/electron-builder.env
          APPLE_ASC_PROVIDER=$(grep '^APPLE_ASC_PROVIDER=' apps/app/electron-builder.env | cut -d '=' -f2-)
          APPLE_ID_PASSWORD=$(grep '^APPLE_ID_PASSWORD=' apps/app/electron-builder.env | cut -d '=' -f2-)
          echo "APPLE_TEAM_ID=$APPLE_ASC_PROVIDER" >> apps/app/electron-builder.env
          echo "APPLE_APP_SPECIFIC_PASSWORD=$APPLE_ID_PASSWORD" >> apps/app/electron-builder.env
      - name: Build - Windows
        if: matrix.runner_label == 'windows-nexus'
        run: |
          $env:NODE_OPTIONS="--max-old-space-size=4096"
          $env:LOCALAPPDATA=""
          npx nx build:win app --publish never --output-style stream --no-cloud
      - name: Build - Mac
        if: matrix.runner_label == 'macos-m-nexus'
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npx nx build:mac app --publish never --universal --output-style stream --no-cloud
      - name: Build - Linux
        if: matrix.runner_label == 'linux-nexus'
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npx nx build:linux app --publish never --output-style stream --no-cloud
      - name: Signing via Digicert
        if: matrix.runner_label == 'windows-nexus'
        env:
          SM_HOST: ${{ secrets.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: "C:\\actions-runner\\certs\\Certificate_pkcs12.p12"
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
        run: |
          SET SM_HOST=%SM_HOST%
          SET SM_API_KEY=%SM_API_KEY%
          SET SM_CLIENT_CERT_FILE=%SM_CLIENT_CERT_FILE%
          SET SM_CLIENT_CERT_PASSWORD=%SM_CLIENT_CERT_PASSWORD%
          SET SM_CODE_SIGNING_CERT_SHA1_HASH=%SM_CODE_SIGNING_CERT_SHA1_HASH%
          SET PATH=%PATH%;"C:\Program Files\DigiCert\DigiCert One Signing Manager Tools"
          SET PATH=%PATH%;"C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64"
          signtool.exe sign /sha1 d97e495588849003df261b9770f4fb820bfe2d55 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 ./apps/app/release/Mudita-Center.exe
        shell: cmd
