name: Build and push artifacts to nexus

on:
  push:
    branches:
      - nexus-poc

jobs:
  Build and Push:
    runs-on: macOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3
      - name: Run Setup
        run: npm run setup
      - name: Install sanitize
        run: npm install sanitize-filename
      - name: TEMP Copy electron-builder
        run: cp ~/electron-builder.env packages/app/electron-builder.env
      - name: Build App
        env:
          PHRASE_API_KEY: ${{ vars.PHRASE_API_KEY }}
          PHRASE_API_URL: ${{ vars.PHRASE_API_URL }}
          PHRASE_API_KEY_DEV: ${{ vars.PHRASE_API_KEY_DEV }}
          MUDITA_CENTER_SERVER_URL: ${{ vars.MUDITA_CENTER_SERVER_URL }}
          ROLLBAR_TOKEN: ${{ vars.ROLLBAR_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ vars.MC_GITHUB_ACCESS_TOKEN }}
          LOGIN_MICROSOFT_ONLINE_CLIENT_ID: ${{ vars.LOGIN_MICROSOFT_ONLINE_CLIENT_ID }}
          FONTS_DIRECTORY_URL: ${{ vars.FONTS_DIRECTORY_URL }}
          FRESHDESK_API_URL: ${{ vars.FRESHDESK_API_URL }}
          FRESHDESK_API_TOKEN: ${{ vars.FRESHDESK_API_TOKEN }}
          ANALYTICS_API_URL: ${{ vars.ANALYTICS_API_URL }}
          ANALYTICS_API_SITE_ID: ${{ vars.ANALYTICS_API_SITE_ID }}
          FEATURE_TOGGLE_ENVIRONMENT: ${{ vars.FEATURE_TOGGLE_ENVIRONMENT }}
          STATIC_CONFIGURATION_FILE_PATH: ${{ vars.STATIC_CONFIGURATION_FILE_PATH }}
          DEV_REDUX_LOGGER_ENABLED: ${{ vars.DEV_REDUX_LOGGER_ENABLED }}
          DEV_DEVICE_LOGGER_ENABLED: ${{ vars.DEV_DEVICE_LOGGER_ENABLED }}
          FEATURE_TOGGLE_RELEASE_ENVIRONMENT: ${{ vars.FEATURE_TOGGLE_RELEASE_ENVIRONMENT }}
          MUDITA_CENTER_PRERELEASE_ENABLED: ${{ vars.MUDITA_CENTER_PRERELEASE_ENABLED }}
        run: cd packages/app/ && npm run dist:prod:all
      - name: Push App to nexus registry
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: printenv && curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file ./packages/app/release/Mudita-Center.exe  https://nexus.mudita.com/repository/mudita-center/releases/Mudita-Center.exe
