name: Build and push artifacts to nexus

on:
  push:
    branches:
      - nexus-poc

jobs:
  build:
    runs-on: macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3

      - name: Install dependencies
        run: npm install
